BEGIN
    FOR c IN (SELECT CUSTOMER_ID, BALANCE FROM CUSTOMERS) LOOP
        IF c.BALANCE > 10000 THEN
            UPDATE CUSTOMERS
            SET ISVIP = 'TRUE'
            WHERE CUSTOMER_ID = c.CUSTOMER_ID;
        END IF;
    END LOOP;

    COMMIT;
END;
/